##PGSQL-Param
app.db.host=localhost
app.db.port=5432
app.db.name=testDB
app.db.username=root
app.db.password=root@123
app.db.pgsql.url.schema=jdbc:postgresql://
#app.db.pgsql.url.query=?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
#&useSSL=false
##
###Hibernate
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
##Datasource Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/testDB
spring.datasource.url=${app.db.pgsql.url.schema}${app.db.host}:${app.db.port}/${app.db.name}
spring.datasource.username=${app.db.username}
spring.datasource.password=${app.db.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=100
###