CREATE TABLE passenger
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             BIGINT,

    created_date        DATE,
    last_modified_date  DATE,

    created_by          VARCHAR(255),
    last_modified_by    VARCHAR(255),

    name                VARCHAR(255) NOT NULL,
    sex                 VARCHAR(20),
    age                 INTEGER,
    dob                 DATE,
    active              BOOLEAN
);

CREATE TABLE person
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version             BIGINT,

    created_date        DATE,
    last_modified_date  DATE,

    created_by          VARCHAR(255),
    last_modified_by    VARCHAR(255),

    name                VARCHAR(255) NOT NULL,
    sex                 VARCHAR(20),
    age                 INTEGER,
    dob                 DATE,
    active              BOOLEAN
);